# Les volumes
volumes:
  pgdata:
    
# Les services
services:
  node:
    image: "node:20"
    working_dir: /usr/src/app
    # environment:
    #    - NODE_ENV=production
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    ports:
      - "8888:8888"
    command: sh -c "npm install && npm run build && npm run dev"

  db:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d/

  adminer:
    image: adminer
    ports:
      - "8081:8080"