services:
  api.gestion:
    build:
      context: build
      dockerfile: 8.3-cli.Dockerfile

    env_file: ./apiGestion.env

    volumes:
      - ./app:/var/php

    working_dir: /var/php

    ports:
      - "8888:8888"

    command: php -S 0.0.0.0:8888 -t /var/php/public