services:
  # Service RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # Port pour l'interface de gestion Web de RabbitMQ
      - "5672:5672"  # Port AMQP
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - code-execution-net

  # Service API Express
  api:
    build: ./api # Dockerfile dans le dossier ./api
    container_name: api
    ports:
      - "3000:3000" # Port de l'API
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - rabbitmq
    networks:
      - code-execution-net

  # Service Java
  java:
    build: ./worker/java
    container_name: java
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq
    volumes:
      - ./worker/java:/usr/src/worker
    depends_on:
      - rabbitmq
    networks:
      - code-execution-net

networks:
  code-execution-net:
    driver: bridge
