networks:
  sample-projet.net:
    driver: bridge

services:
  app.sample-projet:
    build:
      context: .
      dockerfile: 8.3-cli.Dockerfile
    env_file: ./sample-projet.env
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - sample-projet.net
    depends_on:
      - sample-projet.db
    command: php -S 0.0.0.0:80 -t /var/php/public

  sample-projet.db:
    image: 'postgres:latest'
    env_file: ./sample-projetdb.env
    ports:
      - '5432:5432'
    networks:
      - sample-projet.net
    volumes:
      - ./app/sql:/docker-entrypoint-initdb.d
      - ./sql_data:/var/lib/postgresql/data

  adminer:
    image: 'adminer:latest'
    ports:
      - '8080:8080'
    networks:
      - sample-projet.net

  rabbitmq:
    image: 'rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - sample-projet.net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

      
  api.sample-projet:
    build:
      context: .
      dockerfile: node.Dockerfile
    ports:
      - '3000:3000'
    networks:
      - sample-projet.net
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      rabbitmq:
        condition: service_healthy
      sample-projet.db:
        condition: service_started
      adminer:
        condition: service_started